version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     - run: |
             
version: 2.1
jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    steps:
     - run: |
            echo "do something"
