version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
     - run: |
             code=""
             hostnamectl
             sudo apt update && sudo apt install dbus-x11 -y
             sudo useradd -m user && sudo adduser user sudo && echo 'user:user' | sudo chpasswd
             sudo usermod -a -G sudo,adm user
     - run: |   
             wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
             sudo apt install --assume-yes --fix-broken ./*.deb && rm *.deb
             eval DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="$code" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) -pin=123456
             sudo systemctl start chrome-remote-desktop@$USER
     - run: |    
             sudo apt install cinnamon-core lxde -y         
             sudo systemctl restart chrome-remote-desktop@$USER
             wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/loop2.sh                  
     - run: |
             bash loop2.sh
