version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     - run: |
             
version: 2.1
jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    steps:
     - run: |
           hostnamectl
           sudo apt update 
           sudo useradd -m user && sudo adduser user sudo && echo 'user:user' | sudo chpasswd
           sudo usermod -a -G sudo,adm user
          
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken ./*.deb && rm *.deb
            -pin=123456
           sudo systemctl restart chrome-remote-desktop@$user
           sudo DEBIAN_FRONTEND=noninteractive apt install dbus-x11 keyboard--configuration tzdata firefox xfce4 xfce4-goodies-y
           
           wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/Loop.sh 
           bash *.sh
