
name: main
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Code'
        required: true
        default:
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Creating User to Login
      run: |
           sudo useradd -m user && sudo adduser user sudo && echo 'user:user' | sudo chpasswd
           sudo usermod -a -G sudo,adm user
           
            
          
    - name: Start Chrome Remote Desktop
      run: |
           
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken ./*.deb && rm *.deb
           ${{ github.event.inputs.auth }} -pin=123456
           sudo apt-get install xfce4 xfce4-goodies -y 
          
           
           sudo apt install iputils-ping -y
           ping 127.0.0.1
